FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_API_BASE_URL=http://35.238.255.174:8000/api/v1
ARG VITE_REQUEST_TIMEOUT_MS=20000
ARG VITE_SESSION_WARNING_SECONDS=120
ARG VITE_SWITCH_PORTAL_URL=
ARG VITE_ENABLE_P2P_IDEMPOTENCY=false

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_REQUEST_TIMEOUT_MS=$VITE_REQUEST_TIMEOUT_MS
ENV VITE_SESSION_WARNING_SECONDS=$VITE_SESSION_WARNING_SECONDS
ENV VITE_SWITCH_PORTAL_URL=$VITE_SWITCH_PORTAL_URL
ENV VITE_ENABLE_P2P_IDEMPOTENCY=$VITE_ENABLE_P2P_IDEMPOTENCY

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
